server:
  port: 9091

spring:
  application:
    name: HOTEL-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/micro_hotel_detail
    username: root
    password: Hridayesh1@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  config:
    import: configserver:http://localhost:9094

okta:
  oauth2:
    issuer: https://dev-57064256.okta.com/oauth2/default
    audience: api://default

