server:
  port: 9091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/micro_hotel_detail
    username: root
    password: Hridayesh1@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


