server:
  port:
    9092

spring:
  application:
    name: RATING-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: micro_Rating_service

  config:
    import: configserver:http://localhost:9094
okta:
  oauth2:
    issuer: https://dev-57064256.okta.com/oauth2/default
    audience: api://default
